export const SEARCH_BOOK = 'SEARCH_BOOK'
export const GET_SEARCH_RECORD = 'GET_SEARCH_RECORD'
export const SET_SEARCH_RECORD = 'SET_SEARCH_RECORD'
export const CLEAR_SEARCH_RECORD = 'CLEAR_SEARCH_RECORD'